<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $created_by;

    protected $fillable = ['name', 'description', 'type', 'anonymous', 'user_id', 'created_by'];
    protected $UpdateFields = [
        [
            'name'      => 'title',
            'label'     => 'Assunto',
            'type'      => 'input',
            'required'  => true,
            'autofocus' => true
        ],
        [
            'name'      => 'description',
            'label'     => 'Descrição',
            'type'      => 'text',
            'required'  => true,
            'autofocus' => false
        ],
        [
            'name'      => 'type',
            'label'     => 'Impacto',
            'type'      => 'select',
            'options'   => [
                'lookup' => 'types',
                'key' => 'id',
                'value' => 'name'
            ],
            'required'  => true,
            'autofocus' => false,
        ],
        [
            'name'      => 'anonymous',
            'label'     => 'Informar funcionário afetado?',
            'type'      => 'checkbox',
            'values'    => ['checked' => 1, 'unchecked' => 0],
            'required'  => false,
            'autofocus' => false,
        ],
        [
            'dependent' => [
                'field' => 'anonymous',
                'value' => 0,
            ],
            'name'      => 'user_id',
            'label'     => 'Funcionário afetado',
            'type'      => 'select',
            'options'   => [
                'lookup' => 'lookupUser',
                'key' => 'id',
                'value' => 'name'
            ],
            'required'  => false,
            'autofocus' => false,
        ],
    ];
    protected $ExibitionFields = [
        [
            'value' => 'title',
            'label' => 'Assunto',
        ],
        [
            'value' => 'description',
            'label' => 'Descrição',
        ],
        [
            'value' => 'type',
            'label' => 'Tipo',
            'text'  => 'GetTypeText',
        ],
        [
            'value' => 'anonymous',
            'label' => 'Func. afetado',
        ],
        [
            'value' => 'created_by',
            'label' => 'Criador',
        ],
    ];

    public function Creator(){
        return $this->belongsTo('App\User', 'created_by')->first();
    }

    public function User(){
        return $this->belongsTo('App\User', 'user_id')->first();
    }

    public function lookupUser(){
        return User::all();
    }
    public function update(array $attributes = [], array $options = [])
    {
        $attributes['created_by'] = $this->created_by;
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function GetTypeText( Note $note ){
        switch ($note->type){
            case 'N' : $text = 'Negativa'; break;
            case '0' : $text = 'Neutra'; break;
            case 'P' : $text = 'Positiva'; break;
        }
        return $text;
    }

}
