<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $created_by;

    protected $fillable = ['name', 'description', 'type', 'anonymous', 'user_id', 'created_by'];

    public function Creator(){
        return $this->belongsTo('App\User', 'created_by')->first();
    }

    public function User(){
        return $this->belongsTo('App\User', 'user_id')->first();
    }

    public function lookupUser(){
        return User::all();
    }
    public function update(array $attributes = [], array $options = [])
    {
        $attributes['created_by'] = $this->created_by;
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function GetTypeText( Note $note ){
        switch ($note->type){
            case 'N' : $text = 'Negativa'; break;
            case '0' : $text = 'Neutra'; break;
            case 'P' : $text = 'Positiva'; break;
        }
        return $text;
    }

}
